export const KNOWN_TYPES = {
  'Venusaur':     ['Grass','Poison'],  'Charizard':    ['Fire','Flying'],
  'Blastoise':    ['Water'],           'Gengar':       ['Ghost','Poison'],
  'Gyarados':     ['Water','Flying'],  'Dragonite':    ['Dragon','Flying'],
  'Tyranitar':    ['Rock','Dark'],     'Gardevoir':    ['Psychic','Fairy'],
  'Garchomp':     ['Dragon','Ground'], 'Lucario':      ['Fighting','Steel'],
  'Hydreigon':    ['Dark','Dragon'],   'Volcarona':    ['Bug','Fire'],
  'Greninja':     ['Water','Dark'],    'Aegislash':    ['Steel','Ghost'],
  'Sylveon':      ['Fairy'],           'Goodra':       ['Dragon'],
  'Dragapult':    ['Dragon','Ghost'],  'Incineroar':   ['Fire','Dark'],
  'Primarina':    ['Water','Fairy'],   'Toxapex':      ['Poison','Water'],
  'Mimikyu':      ['Ghost','Fairy'],   'Corviknight':  ['Flying','Steel'],
  'Hatterene':    ['Psychic','Fairy'], 'Kingambit':    ['Dark','Steel'],
  'Meowscarada':  ['Grass','Dark'],    'Skeledirge':   ['Fire','Ghost'],
  'Quaquaval':    ['Water','Fighting'],'Garganacl':    ['Rock'],
  'Tinkaton':     ['Fairy','Steel'],   'Palafin':      ['Water'],
  'Archaludon':   ['Steel','Dragon'],  'Pelipper':     ['Water','Flying'],
  'Whimsicott':   ['Grass','Fairy'],   'Hippowdon':    ['Ground'],
  'Torkoal':      ['Fire'],            'Amoonguss':    ['Grass','Poison'],
  'Togekiss':     ['Fairy','Flying'],  'Clefable':     ['Fairy'],
  'Scizor':       ['Bug','Steel'],     'Heracross':    ['Bug','Fighting'],
}